name: "Validate PR"

on:
  pull_request:
    branches: [ "master", "master-github_actions_test", "lsp4helidon" ]
  #to run manually
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'
  HELIDON_PIPELINES: 'true'
  MAVEN_HTTP_ARGS: '-Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3'
  MAVEN_TOOLCHAIN_ARGS: '-Djdk.toolchain.version='${{ JAVA_VERSION }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  copyright:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Copyright
        run: etc/scripts/copyright.sh
  checkstyle:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Checkstyle
        run: etc/scripts/checkstyle.sh
#  docs:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: ${{ env.JAVA_DISTRO }}
#          java-version: ${{ env.JAVA_VERSION }}
#          cache: maven
#      - name: Docs
#        run: etc/scripts/site.sh
#  spotbugs:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: ${{ env.JAVA_DISTRO }}
#          java-version: ${{ env.JAVA_VERSION }}
#          cache: maven
#      - name: Spotbugs
#        run: etc/scripts/spotbugs.sh
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-20.04
            build_script: etc/scripts/build.sh
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Maven build
        run: ${{ matrix.build_script }}